-- create schema solar;
drop table if exists solar.repd;
create table solar.repd (
  old_repd_id varchar(15),
  repd_id integer,
  record_last_updated date,
  tech_type varchar(40),
  storage_type varchar(40),
  co_location_repd_id varchar(10),
  capacity varchar(8),
  chp_enabled varchar(3),
  ro_banding varchar(10),
  fit_tariff varchar(10),
  cfd_capacity varchar(10),
  turbine_capacity varchar(10),
  num_turbines varchar(10),
  height_turbines varchar(10),
  mounting_type varchar(10),
  dev_status varchar(40),
  dev_status_short varchar(30),
  county varchar(30),
  region varchar(20),
  country varchar (20),
  postcode varchar(15),
  x varchar(10),
  y varchar(10),
  planning_authority varchar(70),
  appeal_reference varchar(50),
  sec_state_ref varchar(50),
  type_sec_state_intervention varchar(20),
  judicial_review integer,
  offshore_wind_round varchar(10),
  planning_application_submitted date,
  planning_application_withdrawn date,
  planning_permission_refused date,
  appeal_lodged date,
  appeal_withdrawn date,
  appeal_refused date,
  appeal_granted date,
  planning_permission_granted date,
  sec_state_intervened date,
  sec_state_refused date,
  sec_state_granted date,
  planning_permission_expired date,
  under_construction date,
  operational date,
  primary key (repd_id)
);
copy solar.repd
from '/Users/echalstrey/projects/solar-panel-detection/data/raw/repd_modified.csv' delimiter ',' header csv;
